apiVersion: v1
kind: Service
metadata:
  name: splunk-idxc-slaves-site1
  labels:
    app: splunk
    role: splunk-idxc-slave
    tier: data
    site: "2"
  namespace: splunk-provider
spec:
  ports:
  - port: 9997
    name: s2s

  clusterIP: None
  selector:
    app: splunk
    role: splunk-idxc-slave
    tier: data
    site: "1"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: splunk-idxc-slave-site1
  namespace: splunk-provider
  labels:
    app: splunk
    role: splunk-idxc-slave
    tier: data
    site: "1"
spec:
  selector:
    matchLabels:
      app: splunk
      role: splunk-idxc-slave
      tier: data
      site: "1"
  serviceName: "splunk-idxc-slave-site1"
  replicas: 2
  template:
    metadata:
      labels:
        app: splunk
        role: splunk-idxc-slave
        tier: data
        site: "1"
    spec:
      terminationGracePeriodSeconds: 300
      dnsPolicy: ClusterFirst
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - us-west-1a
                  - us-west-2a
                  - us-east-1a
                  - us-east-2a

      hostname: master
      containers:
      - name: splunk-idxc-master
        image: rfaircloth/cloudsiem-splunk:latest
        ports:
        - containerPort: 9887
          name: splunkrepl
        - containerPort: 9997
          name: splunks2s
        - containerPort: 8089
          name: splunkmgmt
        volumeMounts:
        - name: splunk-etc
          mountPath: /opt/splunk/etc
        - name: splunk-log
          mountPath: /opt/splunk/var/log
        - name: splunk-index
          mountPath: /opt/splunk/var/index
        - name: splunk-run
          mountPath: /opt/splunk/var/run
        - name: splunk-spool
          mountPath: /opt/splunk/var/spool
        env:
        - name: APP
          value: splunk
        - name: ROLE
          value: splunk-idxc-slave
        - name: SPLUNK_GEN_PASS4SYM
          value: genpass
        - name: SPLUNK_ADMIN_USER
          value: admin
        - name: SPLUNK_ADMIN_PASSWORD
          value: Changed@11
        - name: SPLUNK_IDXC_PASS4SYM
          value: idxcpass
        - name: SPLUNK_IDXC_SITE
          value: "1"
        - name: SPLUNK_IDXC_MASTER
          value: https://splunk-idxc-master.splunk-provider.svc.cluster.local:8089

      volumes:
      - name: splunk-run
        emptyDir: {}
      - name: splunk-spool
        emptyDir: {}
      - name: splunk-log
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: splunk-etc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "gp2"
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: splunk-index
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "gp2"
      resources:
        requests:
          storage: 100Gi
