apiVersion: v1
kind: Service
metadata:
  name: splunk-idxc-slaves
  labels:
    app: splunk
    role: splunk-idxc-slave
    tier: data
  namespace: splunk-provider
spec:
  ports:
  - port: 9997
    name: s2s

  clusterIP: None
  selector:
    app: splunk
    role: splunk-idxc-slave
    tier: data
