kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mittwald:secret-generator
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mittwald:secret-generator
roleRef:
  kind: ClusterRole
  name: mittwald:secret-generator
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: secret-generator
    namespace: kube-system
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: secret-generator
  namespace: kube-system