version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04

    environment:
#      TEST_REPORTS: /tmp/test-reports
      KOPS_STATE_STORE: s3://cloudsiem-kops

    working_directory: ~/my-project

    steps:
      - checkout

      - run:
          command: sudo sh build-scripts/install-dependencies.sh

  #    - save_cache:
  #        key: v1-my-project-{{ checksum "project.clj" }}
  #        paths:
  #          - ~/.m2

      # Save artifacts
 #     - store_artifacts:
 #         path: /tmp/artifacts
 #         destination: build

      # Upload test results
 #     - store_test_results:
 #         path: /tmp/test-reports

#  deploy-prod:
#    docker:
#      - image: ubuntu:14.04
#    working_directory: /tmp/my-project
#    steps:
#      - run:
#          name: Deploy if tests pass and branch is Master
#          command: ansible-playbook site.yml -i production

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
 #     - deploy-prod:
 #         requires:
 #           - build
 #         filters:
 #           branches:
 #             only: master
