---
ansible_post_tasks: null
ansible_pre_tasks: null
config:
  baked: default.yml
  defaults_dir: /tmp/defaults
  env:
    headers: null
    var: SPLUNK_DEFAULTS_URL
    verify: true
  host:
    headers: null
    url: null
    verify: true
  max_delay: 60
  max_retries: 3
  max_timeout: 1200
hide_password: false
retry_num: 50
splunk:
  app_paths:
    default: /opt/splunk/etc/apps
    httpinput: /opt/splunk/etc/apps/splunk_httpinput
    idxc: /opt/splunk/etc/master-apps
    shc: /opt/splunk/etc/shcluster/apps
  apps:
    deployment:
      path: /opt/splunk/etc/deployment-apps
    local:
      path: /opt/splunk/etc/apps
    master:
      path: /opt/splunk/etc/master-apps
    shcluster:
      path: /opt/splunk/etc/shcluster/apps
  enable_service: false
  exec: /opt/splunk/bin/splunk
  group: splunk
  hec_disabled: 0
  hec_enableSSL: 1
  hec_port: 8088
  hec_token: 50fe290b-42af-41ea-be1a-1fdcd095eab5
  home: /opt/splunk
  http_enableSSL: 0
  http_enableSSL_cert: null
  http_enableSSL_privKey: null
  http_enableSSL_privKey_password: null
  http_port: 8000
  idxc:
    enable: true
    label: prdsvc
    replication_factor: 3
    replication_port: 4001
    search_factor: 3
    secret: M09KyzAxeR8/qu/2rn6cHXMSimtkoiVZ
  opt: /opt
  password: 6V1hI20mZMtpdjZfAx3kSnYZ0/GDCEfj
  pid: /opt/splunk/var/run/splunk/splunkd.pid
  s2s_enable: true
  s2s_port: 9997
  shc:
    enable: false
    label: shc_label
    replication_factor: 3
    replication_port: 4001
    secret: ctm87fgIUr2yqLVcdyPpb7sJPPKDa8Ng
  smartstore: null
  svc_port: 8089
  user: splunk
splunk_home_ownership_enforcement: true
